### ISSUE TITLE
Create a script to collect repositories provided a given language

### ISSUE THREAD

**Issue by mrthankyou** [JLLeitschuh/lgtm_hack_scripts#5]
One feature I would really like to see is the ability to follow repos provided a given language. For example, the following script would follow as many repositories as possible that use the Java language:

```
python3 follow_repos_by_language.py Java
```

Lingering questions:
- Because this can result in at least a thousand repos to be followed (I think that's what Github API returns to us, will need to double check), do we need to worry about throttling or forbidden responses after a certain number of requests? I don't have much experience running these scripts for LOTS of repositories so I don't have that answer.
- Is this a worthwhile issue to resolve?

**Comment by JLLeitschuh** [comment]
There's a difference between "give me 1k Java repos" and "give me 1k interesting Java repos". You can kinda use the trending API for this, but that's only what's getting the most stars over time. Maybe following the top 1k by star count would be useful?

**Comment by mrthankyou** [comment]
That could work. I'll see what else Github can offer to give us "interesting" repos.

I'm also curious if searching for repos via a keyword is worthwhile. For example, I have a query right now for codeql-go that looks for a misconfigured use of the jwt-go library. By searching for "jwt-go", I can get a list of repositories that potentially use "jwt-go". Considering my experience with codeql is limited at this time, I don't know if this specific search (looking for repos giving a keyword) is worth it but just thought to bring it up.

**Comment by mrthankyou** [comment]
Having done some initial testing, I was able to add the top 1000 starred repositories for a specific language, in my case I choose the Go language. I'll think about how we can get more "interesting" projects and if the query can be improved. Then I'll create a PR for this in the next few days and we can discuss it further. How does that sound?

**Comment by JLLeitschuh** [comment]
Sounds good to me!
