### ISSUE TITLE
Add fork:false to Github search queries

### ISSUE THREAD

**Issue by mrthankyou** [JLLeitschuh/lgtm_hack_scripts#8]
According to @gagliardetto in his [lgtm-cli repo](https://github.com/gagliardetto/lgtm-cli),

> NOTE: lgtm.com does not support fork scanning, so to get more relevant repositories, it's always advised to include fork:false in your search query.

We should consider adding this to the queries in all of our scripts. The change shouldn't be difficult to implement.

I can implement this change once #7 is merged in.

**Comment by JLLeitschuh** [comment]
SGTM!
